version: '3'

services:
  app:
    build: .  
    environment:
      - PORT=3000
    networks:
      - app-network
    command: sh -c "wait-for db:3306 -t 40 -- npm run migrations && npm start"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    volumes:
      - mysql-app-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mainuser
      - MYSQL_PASSWORD=password
    networks:
      - app-network

  nginx:
    image: nginx:1.15.0-alpine
    ports:
      - 8080:80
    networks:
      - app-network
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  mysql-app-data: